export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_DATE_RANGE_FILTER = 'CHANGE_DATE_RANGE_FILTER'

export const CHANGE_ARTICLES_SELECT_FILTER = 'CHANGE_ARTICLES_SELECT_FILTER'